### ISSUE TITLE
Dataset models should determine how they are added to the map panel

### ISSUE THREAD

**Issue by danlamanna** [Kitware/minerva#157]
Right now MapPanel.js is an area where each individual dataset needs to define how it gets rendered within one if statement. This should be generalized in some manner, maybe an individual dataset model can specify it's own ```addDataset``` which will handle the rendering.

**Comment by aashish24** [comment]
@danlamanna I am not sure if having a addDataSet int he model itself would be the best thing. Some alternate solution would be:

1. have some sort of mapper objects that can take the data and the map?
2. have some sort of layer util which can generate new layers depending on the dataset type?

**Comment by mgrauer** [comment]
Yes, this is a constant sore spot.  You can see that I went [back](https://github.com/Kitware/minerva/commit/2dca2b2967cd354c64e899640f375d5daaa925e9) and [forth](https://github.com/Kitware/minerva/commit/3ce632fa405d2de7f8b7b56f20a7301263012ae7) on this very issue when we built support for WMS layers in #115.

I don't like the idea of defining it in the model, since that seems to violate MVC separation, and is the reason I moved the WMS rendering back to the MapPanel.

Having the mapper/layer util is probably the best path forward.  Some dataset types like contour are lucky enough that they can just provide a reader.  Geojson works like this in the general case, but if you want to do anything custom to the rendering, this [isn't so straightforward](https://github.com/Kitware/minerva/pull/143#issuecomment-146874023).

It might be nice to wait until we have one or two more dataset types before refactoring this to get a better sense of the needs.

Related issues

  * a dataset type will have to provide a way to remove itself from the map
  * if/when we split out the legend from the map, datasets will need to specify how to add/remove from the legend
  * any new dataset type will have to define a reader/mapper
  * we will need to define a similar and related path for datasets to display on time serious plots
  * where do we store all of the properties that specify how we want the dataset rendered (e.g. color tied to a particular field, or opacity)?  they probably don't belong on the dataset itself, maybe in some object tied to the dataset and stored in the session?

@danlamanna if you have a dataset type not already in master, please report on the relevant details for how it is working for you.  Also I'm curious to get your take on this w.r.t. time series plots.

**Comment by mgrauer** [comment]
After looking at #205, I have some new thoughts for direction here.

1. Introduce Layer or LayerView objects that understand how different map layers work, and can have the appropriate layer type created for a dataset.  These are Rendering Adapters that are specific to the Dataset type and also to the fact that the Dataset is being rendered in a GeoJs map.
2. Create a Sandwich Model that holds an ordered list of these layers
  * for most cases this will have a special basemap layer at the "bottom"
  * for the initial implementation this will have a special UI layer at the "top"
3. The sandwich has an api like
  * add (dataset or layer, not sure wich yet, probably a layer based on the dataset)
  * remove
  * move up X
  * move down X
  * change opacity (if supported by the layer)
  * possibly some legend related APIs
  * possibly some feature related APIs
4. The sandwich stores state (probably not GeoJs layers, but the properties of the layers that are not included in the dataset), and is saved in the session
5. The Session object saves the state of the sandwich
6. The SessionPanel and MapPanel, both being views, listens for events from the sandwich and update their view state accordingly

There might be better names than Sandwich, but I doubt it. :fork_and_knife: 

I think this is a better direction than what we are currently doing, but needs to be cleaned up a bit to ensure better separation of models from views.  It is still a bit unclear to me where the reference to the GeoJs layers will be held.  Will these be held in the sandwich by the adapters, or in the MapPanel and there will be some correspondence between the adapter and the GeoJs layer?  In other words, the line separating the adapter from the GeoJs layer is still hazy.

**Comment by kotfic** [comment]
@mgrauer First,  +1 for sandwich which coordinates layers. 

In terms of individual Dataset to Renderer conversion  shouldn't the MapPanel be responsible for rendering a set of fixed interfaces?  These can be implemented as functions on the MapPanel (e.g. ```render_geojson()```,  ```render_maptiles()```,  ```render_contourjson()```, etc...).  If this is the case, rendering datasets fall into two cases:

1. **the Dataset model contains data in a format that doesn't need conversion**
    the Dataset model can implement that interface and be passed directly to the MapPanel, no adapter needed. 

2. **the Dataset model contains data that has to be converted before it is rendered**
  the Dataset should be wrapped in an Adapter that implements the interface needed by one of the ```render_*``` functions 

Obviously javascript doesn't have built in functionality for interfaces,  but we can skip it by having  a ```LayerModel``` track this information with tuples of ```minerva.MapPanel.render_*``` function and the ```Adapter/Dataset``` that implements that Interface needed by that function.  The individual ```LayerModel``` objects are managed by the SessionPanel's sandwhich Model.  This makes rendering easy because if you are going to render a layer you just take the first argument of the tuple and call it on the second argument. 

**Example**

I have a ```PointDataset``` that models point data,  it extends ```GeoJSONDataset``` because it's underlying data representation is GeoJSON.  In the DatasetPanel I render a view on this model that has two buttons,  One renders the data as points,  one renders the data as a 2D KDE plot.  When I click on the 'points'  button I add a LayerModel with ```(minerva.MapPanel.render_geojson,  this.model)```  to the sandwhich model on SessionPanel (keep in mind that ```this``` refers to the DatasetView with the two buttons).   If I click on the KDE button I add a LayerModel with the tuple ```(minvera.MapPanel.render_contourjson,  KDEAdapater(this.model))```  where ```KDEAdapter``` implements functions necessary to turn the point data into contour data following the KDE algorithm.  

In some cases that Adapater will be a pure javascript transformation,  but in many cases (e.g,  KDEAdapater)  it will need to call out to the server to do the heavy lifting.  I would recommend ```SynchronousAdapter``` and ```AsynchronousAdapater``` superclasses for all Adapters.  The LayerModel can condition on these types and either call the ```MapPanel.render_*``` function directly on the Adapter/Dataset,  or pass the rendering function as a callback to the adapter,  or Adapater/Datasets can implement an ```is_renderable``` flag and ```AsynchronousAdapaters``` can signal an event when they have finished processing and re-render the layers.

**Comment by jbeezley** [comment]
Mmmm, 🍔

This is what I was talking about in our last meeting (along with #183).  In a more general sense, the views or widgets in minerva should (as much as possible) encode their state in a serializable object so that rendering them is a stateless method that looks like rendering a view in backbone.

I had this concept in mind when I was working on the [jquery plugin](http://opengeoscience.github.io/geojs/apidocs/jQuery.fn.geojsMap.html).  To make this more generally useful, I created static "`create`" methods on several of the core classes ([map](https://github.com/OpenGeoscience/geojs/blob/master/src/core/map.js#L1126), [layer](https://github.com/OpenGeoscience/geojs/blob/master/src/core/layer.js#L618), [feature](https://github.com/OpenGeoscience/geojs/blob/master/src/core/feature.js#L577), etc.) that are meant to work this way.  The spec objects that these methods take are mostly serializable with the exception of the data accessors.  We can (or should rather) consider baking in jspath somehow in geojs to extend the accessors as the are used currently.

**Comment by aashish24** [comment]
> Introduce Layer or LayerView objects that understand how different map layers work, and can have the appropriate layer type created for a dataset. These are Rendering Adapters that are specific to the Dataset type and also to the fact that the Dataset is being rendered in a GeoJs map.

@mgrauer that's what I was referring to mapper like objects (or some registered utils functions). The idea here is that there mappers can take a dataset and create a feature when then can be added to an existing layer or a new layer. It should be possible to register more of these mappers and also you could have multiple mapper to one dataset.
